# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from apexApi import ApexAPI
from dataFrameModel import pandasModel
from PyQt5.QtWidgets import QApplication, QTableView
from PyQt5.QtCore import QAbstractTableModel, Qt

import pandas as pd


class Ui_MainWindow(object):

    def __init__(self):
        self.API = ApexAPI()

    def airPortsClicked(self):
        country = self.airportsLineEdit.text()
        if (country != ""):
            model = pandasModel(self.API.airportsInCountry(country).toPandas())
            self.resultsTextBrowser.setModel(model)
            header = self.resultsTextBrowser.horizontalHeader()
            header.setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)
            self.airportsLineEdit.setText("")

    def airlinesClicked(self):
        unitedStates = self.unitedStatesLineEdit.checkState()
        xStops = self.xstopsLineEdit.text()
        codeShare = self.codeshareLineEdit.checkState()
        model = pandasModel(self.API.Airlines(xStops, codeShare, unitedStates).toPandas())
        header = self.resultsTextBrowser.horizontalHeader()
        header.setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)
        self.resultsTextBrowser.setModel(model)
    
    def aggregationClicked(self):
        countryAirports = self.countryLineEdit.checkState()
        kCities = self.kcitiesLineEdit.text()
        if(countryAirports):
            model = pandasModel(self.API.highestAirportCountry().toPandas())
            header = self.resultsTextBrowser.horizontalHeader()
            header.setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)
            self.resultsTextBrowser.setModel(model)
        elif(kCities != ""):
            self.resultsLabel.setText("Results: Loading")
            model = pandasModel(self.API.topKCities(kCities).toPandas())
            header = self.resultsTextBrowser.horizontalHeader()
            header.setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)
            self.resultsTextBrowser.setModel(model)
            self.resultsLabel.setText("Results: Loaded")


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1060, 700))

        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")

        self.xStopsLabel = QtWidgets.QLabel(self.tab)
        self.xStopsLabel.setGeometry(QtCore.QRect(80, 10, 47, 13))
        self.xStopsLabel.setObjectName("xStopsLabel")

        # x stops input box
        self.xstopsLineEdit = QtWidgets.QLineEdit(self.tab)
        self.xstopsLineEdit.setGeometry(QtCore.QRect(700, 10, 113, 31))
        self.xstopsLineEdit.setObjectName("xstopsLineEdit")

        self.codeShareLabel = QtWidgets.QLabel(self.tab)
        self.codeShareLabel.setGeometry(QtCore.QRect(80, 60, 120, 16))
        self.codeShareLabel.setObjectName("codeShareLabel")

        # codeshare check box
        self.codeshareLineEdit = QtWidgets.QCheckBox(self.tab)
        self.codeshareLineEdit.setGeometry(QtCore.QRect(700, 60, 113, 31))
        self.codeshareLineEdit.setObjectName("codeshareLineEdit")

        self.unitedStatesLabel = QtWidgets.QLabel(self.tab)
        self.unitedStatesLabel.setGeometry(QtCore.QRect(80, 110, 250, 16))
        self.unitedStatesLabel.setObjectName("unitedStatesLabel")

        # united states check box
        self.unitedStatesLineEdit = QtWidgets.QCheckBox(self.tab)
        self.unitedStatesLineEdit.setGeometry(QtCore.QRect(700, 110, 113, 31))
        self.unitedStatesLineEdit.setObjectName("unitedStatesLineEdit")

        # airlines button
        self.airlinesPushButton = QtWidgets.QPushButton(self.tab)
        self.airlinesPushButton.setGeometry(QtCore.QRect(900, 220, 75, 23))
        self.airlinesPushButton.setObjectName("airlinesPushButton")
        self.airlinesPushButton.clicked.connect(self.airlinesClicked)

        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")

        self.airPortsLabel = QtWidgets.QLabel(self.tab_2)
        self.airPortsLabel.setGeometry(QtCore.QRect(80, 20, 200, 13))
        self.airPortsLabel.setObjectName("airPortsLabel")

        # airpoirts input box
        self.airportsLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.airportsLineEdit.setGeometry(QtCore.QRect(700, 10, 113, 31))
        self.airportsLineEdit.setObjectName("airportsLineEdit")

        # airports button
        self.airportsPushButton = QtWidgets.QPushButton(self.tab_2)
        self.airportsPushButton.setGeometry(QtCore.QRect(900, 220, 75, 23))
        self.airportsPushButton.setObjectName("airportsPushButton")
        self.airportsPushButton.clicked.connect(self.airPortsClicked)

        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")

        self.countryMostAirportsLabel = QtWidgets.QLabel(self.tab_3)
        self.countryMostAirportsLabel.setGeometry(
            QtCore.QRect(80, 10, 220, 31))
        self.countryMostAirportsLabel.setObjectName("countryMostAirportsLabel")

        # country input box
        self.countryLineEdit = QtWidgets.QCheckBox(self.tab_3)
        self.countryLineEdit.setGeometry(QtCore.QRect(700, 10, 113, 31))
        self.countryLineEdit.setObjectName("countryLineEdit")

        self.topKCitiesLabel = QtWidgets.QLabel(self.tab_3)
        self.topKCitiesLabel.setGeometry(QtCore.QRect(80, 60, 330, 31))
        self.topKCitiesLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.topKCitiesLabel.setObjectName("topKCitiesLabel")

        # k cities input box
        self.kcitiesLineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.kcitiesLineEdit.setGeometry(QtCore.QRect(700, 60, 113, 31))
        self.kcitiesLineEdit.setText("")
        self.kcitiesLineEdit.setObjectName("kcitiesLineEdit")

        # aggregationPushButton
        self.agreggationPushButton = QtWidgets.QPushButton(self.tab_3)
        self.agreggationPushButton.setGeometry(QtCore.QRect(900, 220, 75, 23))
        self.agreggationPushButton.setObjectName("agreggationPushButton")
        self.agreggationPushButton.clicked.connect(self.aggregationClicked)

        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")

        self.stopsNumberLabel = QtWidgets.QLabel(self.tab_4)
        self.stopsNumberLabel.setGeometry(QtCore.QRect(80, 120, 91, 16))
        self.stopsNumberLabel.setObjectName("stopsNumberLabel")
        # number of stops input box
        self.numberofstopsLineEdit = QtWidgets.QLineEdit(self.tab_4)
        self.numberofstopsLineEdit.setGeometry(QtCore.QRect(700, 110, 113, 31))
        self.numberofstopsLineEdit.setObjectName("numberofstopsLineEdit")

        self.hopsNumberLabel = QtWidgets.QLabel(self.tab_4)
        self.hopsNumberLabel.setGeometry(QtCore.QRect(80, 170, 91, 16))
        self.hopsNumberLabel.setObjectName("hopsNumberLabel")

        self.numberofHopsLineEdit = QtWidgets.QLineEdit(self.tab_4)
        self.numberofHopsLineEdit.setGeometry(QtCore.QRect(700, 160, 113, 31))
        self.numberofHopsLineEdit.setObjectName("numberofHopsLineEdit")

        self.cityYLabel = QtWidgets.QLabel(self.tab_4)
        self.cityYLabel.setGeometry(QtCore.QRect(80, 70, 47, 13))
        self.cityYLabel.setObjectName("cityYLabel")

        self.cityyLineEdit = QtWidgets.QLineEdit(self.tab_4)
        self.cityyLineEdit.setGeometry(QtCore.QRect(700, 60, 113, 31))
        self.cityyLineEdit.setObjectName("cityyLineEdit")

        self.cityXLabel = QtWidgets.QLabel(self.tab_4)
        self.cityXLabel.setGeometry(QtCore.QRect(80, 20, 47, 13))
        self.cityXLabel.setObjectName("cityXLabel")

        self.cityxLineEdit = QtWidgets.QLineEdit(self.tab_4)
        self.cityxLineEdit.setGeometry(QtCore.QRect(700, 10, 113, 31))
        self.cityxLineEdit.setObjectName("cityxLineEdit")

        # Recommendations Button
        self.reccomendationPushButton = QtWidgets.QPushButton(self.tab_4)
        self.reccomendationPushButton.setGeometry(
            QtCore.QRect(900, 220, 75, 23))
        self.reccomendationPushButton.setObjectName("reccomendationPushButton")

        self.resultsTextBrowser = QtWidgets.QTableView(self.centralwidget)
        self.resultsTextBrowser.setGeometry(QtCore.QRect(10, 320, 1060, 350))
        self.resultsTextBrowser.setObjectName("resultsTextBrowser")

        self.resultsLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultsLabel.setGeometry(QtCore.QRect(20, 300, 47, 13))
        self.resultsLabel.setObjectName("resultsLabel")

        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Airport Database"))
        self.airPortsLabel.setText(_translate(
            "MainWindow", "Airports in Country:"))
        self.xStopsLabel.setText(_translate("MainWindow", "X stops:"))
        self.codeShareLabel.setText(_translate("MainWindow", "Code Share:"))
        self.unitedStatesLabel.setText(_translate(
            "MainWindow", "United States Active Airlines:"))
        self.airlinesPushButton.setText(_translate("MainWindow", "Submit"))
        self.airportsPushButton.setText(_translate("MainWindow", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab), _translate("MainWindow", "Airlines"))
        self.countryMostAirportsLabel.setText(_translate(
            "MainWindow", "Country with most airports:"))
        self.topKCitiesLabel.setText(_translate(
            "MainWindow", "Top K cities with most incoming / outgoing airlines:"))
        self.agreggationPushButton.setText(_translate("MainWindow", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_2), _translate("MainWindow", "Airports"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_3), _translate("MainWindow", "Agreggation"))
        self.cityXLabel.setText(_translate("MainWindow", "City X:"))
        self.hopsNumberLabel.setText(
            _translate("MainWindow", "Number of hops: "))
        self.cityYLabel.setText(_translate("MainWindow", "City Y:"))
        self.stopsNumberLabel.setText(
            _translate("MainWindow", "Number of stops: "))
        self.reccomendationPushButton.setText(
            _translate("MainWindow", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_4), _translate("MainWindow", "Trip Reccomendation"))
        self.resultsLabel.setText(_translate("MainWindow", "Results:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
